#!/usr/bin/env bash

# --- CONFIG --------------------------------------------------------
source "./scripts/logger"

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

# --- ERROR CONTROL --------------------------------------------------------

# @description Limpia y notifica fallos.
# shellcheck disable=SC2317
function catch_error() {
	local -r line_number="$1"
	local -r script_name="${BASH_SOURCE[1]:-$0}"
	local -r func_name="${FUNCNAME[1]:-main}"

	logger::err "Error en ${script_name}:${line_number}"
	logger::err "Función: ${func_name}()"
	logger::err "Comando fallido: '${BASH_COMMAND}'"
}

trap 'catch_error $LINENO' ERR

# --- FUNCTIONS -----------------------------------------------------------

# @description Preparación del entorno y carga de configuración
init_configuration() {
	# shellcheck disable=SC2155
	local os_name=$(uname -s)
	local kafve_config_file="./config/kafve.conf"

	case "$os_name" in
	Linux*)
		OS="Linux"
		;;
	Darwin*)
		OS="Mac"
		;;
	CYGWIN* | MINGW* | MSYS*)
		OS="Windows"
		;;
	*)
		OS="Desconocido"
		;;
	esac
	export OS

	if [ -f "$kafve_config_file" ]; then
		set -a
		# shellcheck disable=SC1090
		source "${kafve_config_file}"
		set +a
		echo "-- ${KAFVE_NAME} v${KAFVE_VERSION} (${KAFVE_ENVIRONMENT}) [${OS}] --"
		return 0
	else
		logger::err "No se encontró el archivo 'kafve.conf'."
		exit 1
	fi
}

# @description Punto de entrada principal
main() {
	if [ -z "$1" ]; then
		print_help
	fi

	case "$1" in
	"help" | "-h" | "--help")
		print_help
		;;
	"install")
		./scripts/kafve-install
		./scripts/kafve-dummy-certs generate
		;;
	"uninstall")
		./scripts/kafve-uninstall
		;;
	"broker")
		shift
		./scripts/kafve-broker "$@"
		;;
	"producer")
		shift
		./scripts/kafve-producer "$@"
		;;
	"consumer")
		shift
		./scripts/kafve-consumer "$@"
		;;
	*)
		print_help
		;;
	esac
}

# @description Guía de uso y acciones disponibles.
print_help() {
  cat << EOF

Uso:
    ./kafve <comando> [acción] [opciones]

Comandos Principales:
    help, -h, --help    Muestra esta ayuda.
    install             Instala el proyecto (vía kafve-install).
    clean               Limpia el entorno (vía kafve-uninstall).

--------------------------------------------------------------------------------
$(./scripts/kafve-broker help 2>/dev/null || echo "    [Aviso] No se pudo cargar la ayuda del broker.")
--------------------------------------------------------------------------------
$(./scripts/kafve-consumer help 2>/dev/null || echo "    [Aviso] No se pudo cargar la ayuda del consumer.")
--------------------------------------------------------------------------------
$(./scripts/kafve-producer help 2>/dev/null || echo "    [Aviso] No se pudo cargar la ayuda del producer.")
--------------------------------------------------------------------------------

Configuración:
    Requiere un archivo "kafve.conf" en el directorio ./config.
EOF
  exit 0
}

# --- MAIN -----------------------------------------------------------
logger::warn "Este proyecto está configurado ÚNICAMENTE para DESARROLLO."
logger::warn "Nunca debe usarse en entornos de PRODUCCIÓN por motivos de seguridad."

# Inicializa entorno e importa librería de utilidades comunes
init_configuration

# Punto de entrada principal con paso de argumentos
main "$@"
exit $?
