security.protocol=SSL

# El cliente confía en el servidor (TrustStore)
ssl.truststore.location=config/cert/kafka.broker.truststore.jks
ssl.truststore.password=dummydummy

# El servidor confía en el cliente (KeyStore)
ssl.keystore.location=config/cert/kafka.broker.keystore.jks
ssl.keystore.password=dummydummy
ssl.key.password=dummydummy