# ==========================================
# CONFIGURACIÓN KAFVE
# ==========================================

# Identificación del Script
readonly KAFVE_NAME="KafveDevTool"
readonly KAFVE_VERSION="1.0.0-SNAPSHOT"
readonly KAFVE_ENVIRONMENT="DevTool"

# Configuración y Rutas de Kafka
readonly KAFVE_BROKER_URL="localhost:9093"
readonly KAFVE_KAFKA_DIR="deps/kafka"
readonly KAFVE_KAFKA_CONFIG="config/server.properties"
readonly KAFVE_KAFKA_PRODUCER_CONFIG="config/client.properties"
readonly KAFVE_KAFKA_CONSUMER_CONFIG="config/consumer.properties"
readonly KAFVE_KAFKA_STORAGE_BIN="${KAFVE_KAFKA_DIR}/bin/kafka-storage.sh"
readonly KAFVE_LOG_DIR="log"

# Binarios y Descarga
readonly KAFVE_KAFKA_FILE_NAME="kafka_2.13-4.2.0"
readonly KAFVE_KAFKA_URL="https://downloads.apache.org/kafka/4.2.0/kafka_2.13-4.2.0.tgz"