#!/usr/bin/env bash

# --- CONFIG --------------------------------------------------------
source "./scripts/logger"

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

# --- ERROR CONTROL --------------------------------------------------------

# @description Limpia y notifica fallos.
function catch_error() {
  	local -r line_number="$1"
  	local -r script_name="${BASH_SOURCE[1]:-$0}"

  	logger::err "Error en ${script_name}:${line_number}"
  	logger::err "Comando fallido: '${BASH_COMMAND}'"

	# Funciones de borrado personalizadas dada las funciones
  	[[ -d "${KAFKA_TEMP_DIR}" ]] && rm -rf "${KAFKA_TEMP_DIR}"
  	exit 1
}

trap 'catch_error $LINENO' ERR

# --- VARS --------------------------------------------------------
KAFKA_TEMP_DIR="";

# --- FUNCTIONS --------------------------------------------------------

# @description Ejecuta el flujo de instalación.
function run_install() {
	KAFKA_TEMP_DIR="$(mktemp -d -t kafve.XXXXXX)"
	logger::ok "Carpeta temporal preparada en ${KAFKA_TEMP_DIR}."

	curl -L --ssl-no-revoke --progress-bar "${KAFVE_KAFKA_URL}" -o "${KAFKA_TEMP_DIR}/${KAFVE_KAFKA_FILE_NAME}.tgz"
	logger::ok "Descarga de Kafka finalizada."

	mkdir -p "${KAFVE_KAFKA_DIR}"
	logger::ok "Directorio de instalación configurado."

	tar -xzf "${KAFKA_TEMP_DIR}/${KAFVE_KAFKA_FILE_NAME}.tgz" -C "${KAFVE_KAFKA_DIR}" --strip-components=1
	logger::ok "Archivos extraídos en el destino final -> '${KAFVE_KAFKA_DIR}'"

	rm -rf "${KAFKA_TEMP_DIR}"
	logger::ok "Archivos temporales eliminados."
}

# --- MAIN RUN --------------------------------------------------------
logger::run "Iniciando instalación de Kafve..."
run_install
logger::done "Instalación finalizada en: $(pwd)/${KAFVE_KAFKA_DIR}"