#!/usr/bin/env bash

readonly CERTIFICATE_RUTE="./config/cert"
readonly PASSWORD="dummydummy"
readonly VALIDITY_DAYS=36500
readonly DNAME="CN=localhost, OU=dummy, O=dummy, L=City, S=State, C=ES"

rm -rf "$CERTIFICATE_RUTE"
mkdir -p "$CERTIFICATE_RUTE"

echo "[RUN] Creación de los certificados y credenciales dummy"
### Generar CA Raíz
echo " -[OK] Generando CA Raíz..."
openssl req -new -x509 -days $VALIDITY_DAYS -passout pass:$PASSWORD \
    -keyout "$CERTIFICATE_RUTE/ca-key" -out "$CERTIFICATE_RUTE/ca-cert" -subj "/CN=MyRootCA"

### Generar Keystore del Broker
echo " -[OK] Generando Keystore..."
keytool -genkey -keystore "$CERTIFICATE_RUTE/kafka.broker.keystore.jks" \
    -alias localhost -validity $VALIDITY_DAYS -keyalg RSA \
    -dname "$DNAME" -storepass $PASSWORD -keypass $PASSWORD

### Crear una solicitud de firma (CSR) desde el Keystore
echo " -[OK] Creando solicitud de firma (CSR)..."
keytool -keystore "$CERTIFICATE_RUTE/kafka.broker.keystore.jks" -alias localhost \
    -certreq -file "$CERTIFICATE_RUTE/cert-file-sw" -storepass $PASSWORD

### Firmar el certificado del Broker con nuestra CA Raíz
echo " -[OK] Firmando el certificado con la CA..."
openssl x509 -req \
    -CA "$CERTIFICATE_RUTE/ca-cert" -CAkey "$CERTIFICATE_RUTE/ca-key" \
    -in "$CERTIFICATE_RUTE/cert-file-sw" -out "$CERTIFICATE_RUTE/cert-signed" \
    -days $VALIDITY_DAYS \
    -CAcreateserial -CAserial "$CERTIFICATE_RUTE/ca-cert.srl" \
    -passin pass:$PASSWORD

### Importar la CA y el certificado firmado de vuelta al Keystore
echo " -[OK] Importando CA y certificado firmado al Keystore..."
keytool -keystore "$CERTIFICATE_RUTE/kafka.broker.keystore.jks" -alias CARoot \
    -import -file "$CERTIFICATE_RUTE/ca-cert" -storepass $PASSWORD -noprompt

keytool -keystore "$CERTIFICATE_RUTE/kafka.broker.keystore.jks" -alias localhost \
    -import -file "$CERTIFICATE_RUTE/cert-signed" -storepass $PASSWORD

### Generar Truststore (Para que los clientes confíen en la CA)
echo " -[OK] Generando Truststore..."
keytool -keystore "$CERTIFICATE_RUTE/kafka.broker.truststore.jks" \
    -alias CARoot -import -file "$CERTIFICATE_RUTE/ca-cert" \
    -storepass $PASSWORD -noprompt

echo "[DONE] Ahora la cadena de confianza es completa."