#!/usr/bin/env bash

################################################################################
#                                  MAIN                                        #
################################################################################
main_broker() {
    local force_flag=false

    for arg in "$@"; do
      case "$arg" in
        -f|--force)
          force_flag=true
          break
          ;;
      esac
    done

    case "$1" in
        "init")
            broker_init $force_flag
            ;;
        "start")
            broker_start
            ;;
        "stop")
            broker_stop
            ;;
        "status")
            broker_status
            ;;
        "info")
            broker_info
            ;;
        *)
          return 0
          ;;
    esac
}

# ------------------------------------------------------------------------------
# Inicialización y formateo del broker/cluster
# ------------------------------------------------------------------------------
broker_init() {
    echo "[RUN]  Iniciando configuración del Broker..."

	local force_flag="$1"
    local cluster_id
    local log_dir

    ### Busca el directorio de configuración para Kafka
    if [[ ! -f "$KAFVE_KAFKA_CONFIG" ]]; then
        echo "[Error] No se encuentra el archivo de configuración en $KAFVE_KAFKA_CONFIG"
        return 1
    fi

    ### Toma el directorio para guardar la metadata del cluster de KAFVE_KAFKA_CONFIG (Por defecto un server.properties)
    log_dir=$(grep "^log.dirs=" "$KAFVE_KAFKA_CONFIG" | cut -d'=' -f2 | tr -d '\r')

    ### Verifica y crea si es necesario el directorio .data
    if [[ -d "$log_dir" ]]; then
        if [[ "$force_flag" == true ]]; then
            echo " -[FORCE] Limpiando datos existentes en: $log_dir"
            rm -rf "$log_dir"
            mkdir -p "$log_dir"
        else
            echo "[Error] El directorio $log_dir ya contiene datos."
            echo "[Error] Usa --force si quieres borrar el cluster actual y crear uno nuevo."
            return 1
        fi
    fi

    ### Generación de Id de Cluster Kafka
    cluster_id=$("$KAFVE_KAFKA_STORAGE_BIN" random-uuid)
    if [[ -z "$cluster_id" ]]; then
            echo "[Error] No se pudo generar el Cluster ID"
            return 1
    fi
    echo " -[OK]  Cluster ID generado: $cluster_id"

    ### Formateo del almacenamiento en modo standalone
	if broker_init_run "$cluster_id"; then
		echo " -[OK]  Almacenamiento formateado en modo standalone."
        echo "[DONE]  Configuración del Broker finalizada."
        return 0
    else
    	echo "[ERROR] Se ha producido un error formateando el cluster"
    	exit 1
	fi
}

broker_init_run() {
	local cluster_id="$1"

	"$KAFVE_KAFKA_STORAGE_BIN" format \
        --standalone \
        -t "$cluster_id" \
        -c "$KAFVE_KAFKA_CONFIG"
}

# ------------------------------------------------------------------------------
# Arranque del broker
# ------------------------------------------------------------------------------
broker_start() {
    echo "[RUN]  Inicializando Broker..."

    log_dir=$(grep "^log.dirs=" "$KAFVE_KAFKA_CONFIG" | cut -d'=' -f2 | tr -d '\r')
    if [[ ! -d "$log_dir" ]]; then
        broker_init
    fi

    if jps | grep -q "Kafka"; then
      echo "[DONE-SKIP] El Broker ya ha sido inicializado"
      return 0
    fi

    "${KAFVE_KAFKA_DIR}/bin/kafka-server-start.sh" -daemon config/server.properties;

	sleep 2
    assert_broker_running

    echo "[DONE] Se ha inicializado el broker"
}



# ------------------------------------------------------------------------------
# Parada del broker
# ------------------------------------------------------------------------------
broker_stop() {
    echo "[RUN] Deteniendo Broker..."

    # Señal de parada oficial del broker
    "${KAFVE_KAFKA_DIR}/bin/kafka-server-stop.sh"
    echo " -[TASK] Enviada señal de parada oficial"

    echo " -[WAIT] Esperando finalización del proceso de parada del broker"
    sleep 3
    # Verificación de parada del broker
    if jps | grep -q "Kafka"; then
        # Parada forzada del broker
        echo " [FORCE] El proceso no cerró a tiempo, forzando..."
        pkill -15 -f "kafka.Kafka"
        echo " -[OK] Proceso finalizado por fuerza (SIGTERM)"
    else
        echo " -[OK] El script oficial cerró el Broker correctamente"
    fi

    echo "[DONE] Procedimiento completado."
}

# ------------------------------------------------------------------------------
# Tabla de visualización de estado del broker
# ------------------------------------------------------------------------------
broker_status() {
    echo "[RUN] Consultando estado del Broker..."

    assert_broker_running

    echo "------------------------------------------------------------------------------------"
    printf "| %-8s | %-6s | %-60s |\n" "PID" "ESTADO" "CLUSTER ID (UUID)"
    echo "------------------------------------------------------------------------------------"

    # shellcheck disable=SC2009
    ps -ef | grep -i "kafka.kafka" | grep -v "grep" | while read -r line; do
        print_broker_status_row "$line"
    done
    echo "------------------------------------------------------------------------------------"

    echo "[DONE] Consulta de estado finalizada."
}

print_broker_status_row() {
    local line="$1"
    local label_pid
    local label_cluster_id="Unknown"

    label_pid=$(echo "$line" | awk '{print $2}')

    local log_dir
    log_dir=$(grep "^log.dirs=" "$KAFVE_KAFKA_CONFIG" | cut -d'=' -f2 | tr -d '\r')
    if [[ -f "$log_dir/meta.properties" ]]; then
        label_cluster_id=$(grep "cluster.id" "$log_dir/meta.properties" | cut -d'=' -f2 | tr -d '\r')
    fi

    printf "| %-8s | %-6s | %-60s |\n" "$label_pid" "OK" "$label_cluster_id"
}

# ------------------------------------------------------------------------------
# Visor del log del broker
# ------------------------------------------------------------------------------
broker_info() {
    echo "[RUN] Abriendo visor de logs para broker en tiempo real..."

	# Comprueba si existe archivo de log
    local log_file="${KAFVE_KAFKA_DIR}/logs/server.log"
    if [[ ! -f "$log_file" ]]; then
        echo "[ERROR] No se encuentra el archivo en: $log_file"
        return 1
    fi

    # Comprueba si existen brokers activos
    assert_broker_running

	# info para salir
    echo " -[INFO] Presiona CTRL+C para salir."
    echo "--------------------------------------------------"

    # Entra al visor de logs del broker
    trap 'echo -e "\n[DONE] Has salido del visor de logs del broker"; return' INT
    tail -f "$log_file"

    # Limpiamos la trap al salir para no afectar al resto del script
    trap - INT
}

# Comprueba si existen brokers activos
assert_broker_running() {
	local kafka_jps_data

	kafka_jps_data=$(jps -l | grep -i 'kafka.kafka' )
    if [[ -z $kafka_jps_data ]]; then
        echo "[ERROR] No se han encontrado procesos activos"
        exit 1
    fi
}

################################################################################
#                               MAIN RUN                                       #
################################################################################
main_broker "$@"