#!/usr/bin/env bash

# --- CONFIG --------------------------------------------------------
source "./scripts/logger"

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

# --- ERROR CONTROL --------------------------------------------------------

# @description Limpia y notifica fallos.
function catch_error() {
  	local -r line_number="$1"
  	local -r script_name="${BASH_SOURCE[1]:-$0}"

  	logger::err "Error en ${script_name}:${line_number}"
  	logger::err "Comando fallido: '${BASH_COMMAND}'"
}

trap 'catch_error $LINENO' ERR

# --- VARS -----------------------------------------------------------
readonly BLACK_LIST=("$KAFVE_KAFKA_DIR" "log" ".data")

# --- FUNCTIONS -----------------------------------------------------------
run_clean() {
    logger::run "Iniciando limpieza interna..."

    # TODO: Que pare los consumer y brokers

    for rute in "${BLACK_LIST[@]}"; do
        if [ -e "$rute" ]; then
            rm -rf "$rute"
            logger::ok "'$rute' eliminado con éxito."
        else
            logger::custom "SKIP" "'$rute' no existe, saltando..."
        fi
    done

    logger::done "Limpieza completada."
}

# --- MAIN RUN -----------------------------------------------------------
run_clean