#!/usr/bin/env bash

# --- CONFIG --------------------------------------------------------
# Evitar cargas múltiples.
[[ ${KAFVE__KAFVE_COMMONS_LOADED+true} ]] && return 0

source "./scripts/logger"

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

# --- ERROR CONTROL --------------------------------------------------------

# @description Limpia archivos temporales y notifica fallos en el script.
# @param $1 string Número de línea donde ocurrió el error.
kafve_commons::catch_error() {
	local -r line_number="$1"
	local -r script_name="${BASH_SOURCE[1]:-$0}"

	logger::err "Error en ${script_name}:${line_number}" >&2
	logger::err "Comando fallido: '${BASH_COMMAND}'" >&2

	exit 1
}

trap 'kafve_commons::catch_error $LINENO' ERR

# --- FUNCTIONS -----------------------------------------------------------

# @description Normaliza una ruta eliminando basura de Windows, comillas y espacios.
#              Si detecta Windows, convierte la ruta al formato Unix (Cygwin/MSYS).
# @param $1 string Ruta original a limpiar.
# @stdout string La ruta saneada y normalizada.
kafve_commons::normalize_path() {
	local -r path="$1"
	local normalized_path

	### Extracción y limpieza de la ruta del log (usa herestring para evitar pipes innecesarios)
	normalized_path=$(sed -e 's/\r//g' -e 's/^"//' -e 's/"$//' <<<"${path}" | xargs)

	### Conversión Windows -> Unix
	if [[ "${OS:-}" == "Windows" ]]; then
		normalized_path=$(cygpath -u "${normalized_path}")
	fi

	### Retorna la ruta normalizada
	echo "${normalized_path}"
}

# @description Construye el path al ejecutable de Kafka según el Sistema Operativo.
#              Gestiona automáticamente la subcarpeta /windows/ y la extensión .bat.
# @param $1 string Nombre del script (ej: kafka-topics).
# @param $2 string [Opcional] Directorio base de Kafka (default: ".").
# @stdout string Path relativo o absoluto al script (.sh o .bat).
kafve_commons::get_kafka_script() {
	local -r script_name="$1"
	local -r input_base="${2:-.}"
	local base_path
	local full_path=""

	base_path=$(kafve_commons::normalize_path "${input_base}")

	if [[ "${OS:-}" == "Windows" ]]; then
		full_path="${base_path}/bin/windows/${script_name}.bat"
	else
		full_path="${base_path}/bin/${script_name}.sh"
	fi

	# Limpiar el path si empieza con ./ para que se vea más estético
	echo "${full_path}"
}

# Establece que la librería KAFVE__KAFVE_COMMONS_LOADED ha sido cargada
readonly KAFVE__KAFVE_COMMONS_LOADED=true
