#!/usr/bin/env bash

################################################################################
#                                  MAIN                                        #
################################################################################
main_broker() {
    local force_flag=false

    for arg in "$@"; do
      case "$arg" in
        -f|--force)
          force_flag=true
          break
          ;;
      esac
    done

    case "$1" in
        "init")
            broker_init $force_flag
            ;;
        "start")
            broker_start $force_flag
            ;;
        "stop")
            broker_stop
            ;;
        "status")
            broker_status
            ;;
        "info")
            broker_info
            ;;
        *)
          return 0
          ;;
    esac
}

# ------------------------------------------------------------------------------
# Inicialización y formateo del broker/cluster
# ------------------------------------------------------------------------------
broker_init() {
    echo "[RUN]  Iniciando configuración del Broker..."

	local force_flag="$1"
    local cluster_id
    local log_dir

	### Verifica el estado del broker y lo detiene si está activo
	if is_broker_running; then
	    echo " -[INFO] Broker detectado en ejecución. Deteniendo para reinicialización..."
	    broker_stop
	fi

    ### Busca el directorio de configuración para Kafka
    if [[ ! -f $(kafve_commons::normalize_path "$KAFVE_KAFKA_CONFIG") ]]; then
        echo "[ERROR] No se encuentra el archivo de configuración en $KAFVE_KAFKA_CONFIG" >&2
        exit 1
    fi

    ### Toma el directorio para guardar la metadata del cluster de KAFVE_KAFKA_CONFIG (Por defecto un server.properties)
    log_dir=$(kafve_commons::normalize_path "$(grep "^log.dirs=" "$KAFVE_KAFKA_CONFIG" | head -n 1 | cut -d'=' -f2)")

    ### Verifica y crea si es necesario el directorio .data
    if [[ -d "$log_dir" ]]; then
        if [[ "$force_flag" == true ]]; then
            echo " -[FORCE] Limpiando datos existentes en: $log_dir"
            rm -rf "$log_dir"
            mkdir -p "$log_dir"
        else
            echo "[ERROR] El directorio $log_dir ya contiene datos." >&2
            echo "[ERROR] Usa --force si quieres borrar el cluster actual y crear uno nuevo." >&2
            exit 1
        fi
    fi

    ### Generación de Id de Cluster Kafka
    cluster_id=$($(kafve_commons::get_kafka_script "kafka-storage" "$KAFVE_KAFKA_DIR") random-uuid)
    if [[ -z "$cluster_id" ]]; then
            echo "[ERROR] No se pudo generar el Cluster ID" >&2
            exit 1
    fi
    echo " -[OK]  Cluster ID generado: $cluster_id"

    ### Formateo del almacenamiento en modo standalone
	if broker_init_run "$cluster_id"; then
		echo " -[OK]  Almacenamiento formateado en modo standalone."
        echo "[DONE]  Configuración del Broker finalizada."
        return 0
    else
    	echo "[ERROR] Se ha producido un error formateando el cluster" >&2
    	exit 1
	fi
}

broker_init_run() {
	local cluster_id="$1"
	local script_path

	script_path=$(kafve_commons::get_kafka_script "kafka-storage" "$KAFVE_KAFKA_DIR")
	"$script_path" format \
       --standalone \
       -t "$cluster_id" \
       -c "$KAFVE_KAFKA_CONFIG"
}

# ------------------------------------------------------------------------------
# Arranque del broker
# ------------------------------------------------------------------------------
broker_start() {
	local force_flag="$1"

    echo "[RUN] Inicializando Broker..."

	### Comprueba si existe la carpeta para los logs, especificado en el server.properties
    log_dir=$(kafve_commons::normalize_path "$(grep "^log.dirs=" "$KAFVE_KAFKA_CONFIG" | head -n 1 | cut -d'=' -f2)")
    if [[ ! -d "$log_dir" || "$force_flag" == true ]]; then
        broker_init "$force_flag"
    fi

	### Comprueba si ya hay un broker inicializado
    if is_broker_running; then
      echo "[SKIP] El Broker ya está en ejecución."
      exit 0
    fi

	### Ejecuta el script de inicio del servidor Kafka en segundo plano
    broker_start_run

	### Espera unos segundos y verifica si el proceso se mantiene activo
	sleep 2
	if ! is_broker_running; then
      echo "[ERROR] El Broker no ha podido inicializarse correctamente" >&2
    fi

    echo "[DONE] Se ha inicializado el broker"
}

broker_start_run() {
	local script_path
	script_path=$(kafve_commons::get_kafka_script "kafka-server-start" "$KAFVE_KAFKA_DIR")

	$script_path -daemon config/server.properties
}

# ------------------------------------------------------------------------------
# Parada del broker
# ------------------------------------------------------------------------------
broker_stop() {
    echo "[RUN] Deteniendo Broker..."

    ### Señal de parada oficial del broker
    "$(kafve_commons::get_kafka_script "kafka-server-stop" "$KAFVE_KAFKA_DIR")"
    echo " -[TASK] Enviada señal de parada oficial"

    echo " -[WAIT] Esperando finalización del proceso de parada del broker"
    sleep 3

    ### Verificación de parada del broker
    if jps | grep -q "Kafka"; then
        # Parada forzada del broker
        echo " [FORCE] El proceso no cerró a tiempo, forzando..."
        pkill -15 -f "kafka.Kafka"
        echo " -[OK] Proceso finalizado por fuerza (SIGTERM)"
    else
        echo " -[OK] El script oficial cerró el Broker correctamente"
    fi

    echo "[DONE] Procedimiento completado."
}

# ------------------------------------------------------------------------------
# Tabla de visualización de estado del broker
# ------------------------------------------------------------------------------
broker_status() {
    echo "[RUN] Consultando estado del Broker..."

	if ! is_broker_running; then
	    echo "[ERROR] El Broker no se encuentra activo." >&2
	    exit 1
	fi

    echo "------------------------------------------------------------------------------------"
    printf "| %-8s | %-6s | %-60s |\n" "PID" "ESTADO" "CLUSTER ID (UUID)"
    echo "------------------------------------------------------------------------------------"

    # shellcheck disable=SC2009
    ps -ef | grep -i "kafka.kafka" | grep -v "grep" | while read -r line; do
        print_broker_status_row "$line"
    done
    echo "------------------------------------------------------------------------------------"

    echo "[DONE] Consulta de estado finalizada."
}

print_broker_status_row() {
    local line="$1"
    local label_pid
    local label_cluster_id="Unknown"

    label_pid=$(echo "$line" | awk '{print $2}')

    local log_dir
    log_dir=$(kafve_commons::normalize_path "$(grep "^log.dirs=" "$KAFVE_KAFKA_CONFIG" | head -n 1 | cut -d'=' -f2)")
    if [[ -f "$log_dir/meta.properties" ]]; then
        label_cluster_id=$(grep "cluster.id" "$log_dir/meta.properties" | cut -d'=' -f2 | tr -d '\r')
    fi

    printf "| %-8s | %-6s | %-60s |\n" "$label_pid" "OK" "$label_cluster_id"
}

# ------------------------------------------------------------------------------
# Visor del log del broker
# ------------------------------------------------------------------------------
broker_info() {
    echo "[RUN] Abriendo visor de logs para broker en tiempo real..."

	### Comprueba si existe archivo de log
    local log_file="${KAFVE_KAFKA_DIR}/logs/server.log"
    if [[ ! -f "$log_file" ]]; then
        echo "[ERROR] No se encuentra el archivo en: $log_file" >&2
        return 1
    fi

    ### Comprueba si existen brokers activos
    assert_broker_running

	### info para salir
    echo " -[INFO] Presiona CTRL+C para salir."
    echo "--------------------------------------------------"

    ### Entra al visor de logs del broker
    trap 'echo -e "\n[DONE] Has salido del visor de logs del broker"; return' INT
    tail -f "$log_file"

    ### Limpiamos la trap al salir para no afectar al resto del script
    trap - INT
}

# Verifica si el proceso de Kafka está activo mediante jps
# Retorna 0 (true) si se encuentra 'kafka.kafka', 1 (false) en caso contrario
is_broker_running() {
    jps -l | grep -iq "kafka.kafka"
}

################################################################################
#                               MAIN RUN                                       #
################################################################################
if [[ -f "$(dirname "$0")/kafve-commons" ]]; then
    source "$(dirname "$0")/kafve-commons"
else
    echo "[ERROR] No se encontró '$(dirname "$0")'/kafve-commons. Abortando." >&2
    exit 1
fi

main_broker "$@"