#!/usr/bin/env bash
# --- CONFIG --------------------------------------------------------
source "./scripts/logger"
source "./scripts/kafve-commons"

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

# --- ERROR CONTROL --------------------------------------------------------

# @description Limpia archivos temporales y notifica fallos en el script.
# @param $1 string Número de línea donde ocurrió el error.
consumer::catch_error() {
	local -r line_number="$1"
	local -r script_name="${BASH_SOURCE[1]:-$0}"

	logger::err "Error en ${script_name}:${line_number}" >&2
	logger::err "Comando fallido: '${BASH_COMMAND}'" >&2

	exit 1
}

trap 'consumer::catch_error $LINENO' ERR

# --- FUNCTIONS -----------------------------------------------------------

# @description Punto de entrada principal para el productor de Kafve.
# @param $@ string Argumentos de la línea de comandos.
producer::main() {
	local command=""
	local key="K-$RANDOM$RANDOM"
	local topic="SOMETHING"
	local file_rute=""
	local message=""

	### Procesado de argumentos
	while [[ $# -gt 0 ]]; do
		case "$1" in
		send)
			command="send"
			shift
			;;
		help | -h | --help | "")
			command="help"
			shift
			;;
		-t | --topic)
			topic="$2"
			shift 2
			;;
		-k | --key)
			key="$2"
			shift 2
			;;
		-m | --message)
			message="$2"
			shift 2
			;;
		-f | --file)
			file_rute="$2"
			shift 2
			;;
		*)
			logger::custom "SKIP" "/kafve producer <comando> [argumentos]"
			return 0
			;;
		esac
	done

	# Delegación de comandos
	case "$command" in
	"send")
		producer::send "${topic}" "${key}" "${message}" "${file_rute}"
		;;
	"help")
		producer::help
		return 0
		;;
	*)
		logger::custom "SKIP" "/kafve producer <comando> [argumentos]"
		return 0
		;;
	esac
}

# @description Orquesta las validaciones y el envío del payload al tópico de Kafka.
# @param $1 string Nombre del tópico.
# @param $2 string Clave del mensaje.
# @param $3 string Mensaje de texto plano (opcional).
# @param $4 string Ruta al archivo con el payload (opcional).
producer::send() {
	logger::run "Procesando envío."
	local -r topic="$1"
	local -r key="$2"
	local -r message="$3"
	local -r file_rute="$4"

	### Comprobar que el broker esta levantado y disponible
	if ! ./scripts/kafve-broker status >/dev/null 2>&1; then
		logger::err "El broker de Kafka no está activo o no está disponible."
		return 1
	fi

	### Comprobación de que habrá algo en el payload
	if [[ -z "${message}" && -z "${file_rute}" ]]; then
		logger::err "El payload no debe estar vacío"
		return 1
	fi

	### Comprueba que el tópico existe o intenta crearlo
	if producer::check_topic_exists "${KAFVE_BROKER_CONTROLLER_URL}" "${topic}"; then
		logger::ok "Tópico '${topic}' verificado (ya existe en el servidor)."
	else
		if producer::create_topic "${KAFVE_BROKER_CONTROLLER_URL}" "${topic}"; then
			logger::ok "Tópico '${topic}' creado exitosamente."
		else
			logger::err "Falló la creación del tópico '${topic}'."
			return 1
		fi
	fi

	### Mandar mensaje a partir de un archivo (json, xml, csv...)
	if [[ -n "${file_rute}" ]]; then
		if [[ ! -f "${file_rute}" ]]; then
			logger::err "No se ha podido leer el archivo: ${file_rute}"
			return 1
		fi

		local read_file
		read_file=$(tr -d '\n\r\t' <"${file_rute}")

		if producer::send_message "${topic}" "${key}" "${read_file}"; then
			logger::done "Mensaje entregado correctamente (Key: '${key}')."
			return 0
		else
			logger::err "Error de red o broker: No se pudo entregar el mensaje en '${topic}'."
			return 1
		fi
	fi

	### Mandar mensaje por cadena de texto
	if [[ -n "${message}" ]]; then
		logger::custom "SEND" "Enviando mensaje al tópico '${topic}'..."

		if producer::send_message "${topic}" "${key}" "${message}"; then
			logger::done "Mensaje entregado correctamente (Key: '${key}')."
			return 0
		else
			logger::err "Error de red o broker: No se pudo entregar el mensaje en '${topic}'."
			return 1
		fi
	fi
}

# @description Comprueba si un tópico existe consultando al broker.
# @param $1 string URL del broker de Kafka.
# @param $2 string Nombre del tópico.
producer::check_topic_exists() {
	local -r broker="$1"
	local -r topic="$2"
	local -r script_path=$(kafve_commons::get_kafka_script "kafka-topics" "${KAFVE_KAFKA_DIR:-.}")

	"${script_path}" \
		--bootstrap-server "${broker}" \
		--command-config "${KAFVE_KAFKA_PRODUCER_CONFIG}" \
		--describe \
		--topic "${topic}" >/dev/null 2>&1
}

# @description Crea un nuevo tópico con configuración por defecto (1 partición, factor réplica 1).
# @param $1 string URL del broker de Kafka.
# @param $2 string Nombre del tópico.
producer::create_topic() {
	local -r broker="$1"
	local -r topic="$2"
	local -r script_path=$(kafve_commons::get_kafka_script "kafka-topics" "${KAFVE_KAFKA_DIR:-.}")

	logger::warn "El tópico '${topic}' no existe. Intentando crear..."
	"${script_path}" \
		--create \
		--bootstrap-server "${broker}" \
		--command-config "${KAFVE_KAFKA_PRODUCER_CONFIG}" \
		--topic "${topic}" \
		--partitions 1 \
		--replication-factor 1 >/dev/null 2>&1
}

# @description Ejecuta el cliente nativo de Kafka para transmitir el mensaje.
# @param $1 string Nombre del tópico.
# @param $2 string Clave del mensaje.
# @param $3 string Contenido del mensaje.
producer::send_message() {
	local -r topic="$1"
	local -r key="$2"
	local -r message="$3"
	local -r script_path=$(kafve_commons::get_kafka_script "kafka-console-producer" "${KAFVE_KAFKA_DIR:-.}")

	"${script_path}" \
		--topic "${topic}" \
		--bootstrap-server "${KAFVE_BROKER_CONTROLLER_URL}" \
		--producer.config "${KAFVE_KAFKA_PRODUCER_CONFIG}" \
		--reader-property "parse.key=true" \
		--reader-property "key.separator=:" \
		--producer-property acks=all \
		<<<"${key}:${message}" >/dev/null 2>&1
}

# @description Imprime el menú de ayuda con la descripción detallada de los comandos.
producer::help() {
	cat <<'EOF'
Producer (Gestión de publicación de mensajes):
    Uso: ./kafve producer <acción> [opciones]

    Acciones:
        send <-t tópico> [-k llave] [-m mensaje | -f archivo]
        help, -h        Muestra este panel de asistencia técnica.

    Descripción de Acciones:
        send    Publica un registro en Kafka. Requiere obligatoriamente un tópico
                y contenido (mensaje directo o vía archivo).

    Opciones:
        -t, --topic     Nombre del tópico destino (Obligatorio).
        -m, --message   Cuerpo del mensaje en texto plano.
        -f, --file      Ruta a un archivo (se envía como un único mensaje).
        -k, --key       Llave del mensaje (Opcional, defecto: K-RANDOM).

    Ejemplos:
        ./kafve producer send -t ventas -m "Orden #123"
        ./kafve producer help

EOF
}

# --- MAIN RUN -----------------------------------------------------------
producer::main "$@"
